### ISSUE TITLE
[Crash]: Start up crash

### ISSUE THREAD

**Issue by A5ho9999** [Fuzss/moblassos#1]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v7.0.0-1.20-Fabric

### Notes (Required)

Crash on start when trying to use with 1.20.1 (fabric dependency override)

### Crash Report (Required)

https://gist.github.com/A5ho9999/f9f0a54d88e61f3c22166cc79df5b3e5

**Comment by Fuzss** [comment]
Additionally install this mod for now: https://mega.nz/file/Hd8A1ToB#cNgPvQwHxWzlYNZjrGCJmOG6qYFNyULThJnDtzInclY

**Comment by A5ho9999** [comment]
That works, thanks

**Comment by Fuzss** [comment]
This is fixed for 1.20.1+, 1.20 will is no longer receiving updates.

**Comment by A5ho9999** [comment]
That's fine, we are using 1.20.1 anyway. Thanks!
