### ISSUE TITLE
[Bug]: Villager Pickup

### ISSUE THREAD

**Issue by A5ho9999** [Fuzss/moblassos#2]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

https://modrinth.com/mod/mob-lassos/version/v8.0.0-1.20.1-Fabric

### Notes (Required)

Picking up a villager that is in a bed doesn't quite work, it'll place it back in the bed. (Error if the bed is no longer loaded)

Steps
- Get villager to sleep
- Pick up in Lasso (Use Creative Lasso but assume it affects the emerald as well)
- Place villager back down somewhere else

**Comment by Fuzss** [comment]
Thanks for reporting, fixed in v8.0.1.
