### ISSUE TITLE
[Crash]: Ticking World

### ISSUE THREAD

**Issue by PastellePixie** [Fuzss/moblassos#3]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

MobLassos-v8.0.0

### Notes (Required)

Just play

### Crash Report (Required)

https://gist.github.com/Zykana/aadce5a3163f9289579b44ba51825b6e

**Comment by Fuzss** [comment]
This was fixed in Puzzles Lib v8.1.7.
