### ISSUE TITLE
[Bug]: Attempting to 'respawn' an aggressive mob within range of a Magnum Torch prevents spawn

### ISSUE THREAD

**Issue by GothCartel** [Fuzss/moblassos#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

When you have captured a hostile mob in the appropriate lasso and attempt to 'respawn' it within range of a Magnum Torch it prevents the mob from spawning.

For example if you wished to capture the mob within an Ars Nouveau containment jar to create a passive mob farm you cannot do this if you have a Magnum torch present.

**Comment by Fuzss** [comment]
Thanks for reporting, fixed in v8.0.1.
